#!/usr/bin/env python3
"""Generate the private deployment (#85) from the public app files.

Outputs (all generated, do not edit by hand):
  layers-input.private.json   layers-input.json + private/layers.json
  system-prompt.private.md    system-prompt.md + private/system-prompt-addendum.md
  k8s/private-configmap.yaml  k8s/configmap.yaml renamed, with nginx basic auth
  k8s/private-deployment.yaml k8s/deployment.yaml renamed, copying the private files
                              and mounting the htpasswd Secret

k8s/private-service.yaml and k8s/private-ingress.yaml are hand-written.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = "# GENERATED by scripts/build-private.py from k8s/{src} — do not edit by hand.\n"


def replace_once(text, old, new):
    assert text.count(old) == 1, f"expected exactly one match for {old!r}"
    return text.replace(old, new)


def build_layers():
    public = json.loads((ROOT / "layers-input.json").read_text())
    extra = json.loads((ROOT / "private/layers.json").read_text())
    for entry in extra["collections"]:
        ids = [c["collection_id"] for c in public["collections"]]
        public["collections"].insert(ids.index(entry["insert_after"]) + 1, entry["collection"])
    public["sidebar"]["title"] = public["sidebar"]["title"] + " (private)"
    (ROOT / "layers-input.private.json").write_text(json.dumps(public, indent=4, ensure_ascii=False) + "\n")


def build_prompt():
    text = (ROOT / "system-prompt.md").read_text().rstrip("\n") + "\n"
    text += (ROOT / "private/system-prompt-addendum.md").read_text()
    (ROOT / "system-prompt.private.md").write_text(text)


def build_configmap():
    t = (ROOT / "k8s/configmap.yaml").read_text()
    t = t.replace("name: bosl-high-seas-config", "name: bosl-high-seas-private-config")
    t = t.replace("name: bosl-high-seas-nginx", "name: bosl-high-seas-private-nginx")
    t = replace_once(t, "        root /usr/share/nginx/html;\n        index index.html;\n",
        "        root /usr/share/nginx/html;\n        index index.html;\n\n"
        "        # Private deployment (#85): HTTP basic auth on everything, including\n"
        "        # /api/llm/, except /health (probes). The htpasswd file comes from the\n"
        "        # bosl-high-seas-private-htpasswd Secret and is never committed.\n"
        "        auth_basic \"High Seas Explorer (private)\";\n"
        "        auth_basic_user_file /etc/nginx/auth/htpasswd;\n")
    t = replace_once(t, "        location /health {\n            access_log off;",
        "        location /health {\n            auth_basic off;\n            access_log off;")
    (ROOT / "k8s/private-configmap.yaml").write_text(HEADER.format(src="configmap.yaml") + t)


def build_deployment():
    t = (ROOT / "k8s/deployment.yaml").read_text()
    t = t.replace("bosl-high-seas-config", "bosl-high-seas-private-config")
    t = t.replace("bosl-high-seas-nginx", "bosl-high-seas-private-nginx")
    t = t.replace("name: bosl-high-seas\n", "name: bosl-high-seas-private\n")
    t = t.replace("app: bosl-high-seas\n", "app: bosl-high-seas-private\n")
    t = replace_once(t, "cp /tmp/repo/layers-input.json /usr/share/nginx/html/",
        "cp /tmp/repo/layers-input.private.json /usr/share/nginx/html/layers-input.json")
    t = replace_once(t, "cp /tmp/repo/system-prompt.md /usr/share/nginx/html/",
        "cp /tmp/repo/system-prompt.private.md /usr/share/nginx/html/system-prompt.md")
    t = replace_once(t, "        - name: config-template\n          mountPath: /config\n",
        "        - name: config-template\n          mountPath: /config\n"
        "        - name: htpasswd\n          mountPath: /etc/nginx/auth\n          readOnly: true\n")
    t = replace_once(t, "      - name: nginx-conf-d\n        emptyDir: {}",
        "      - name: nginx-conf-d\n        emptyDir: {}\n"
        "      - name: htpasswd\n        secret:\n          secretName: bosl-high-seas-private-htpasswd")
    (ROOT / "k8s/private-deployment.yaml").write_text(HEADER.format(src="deployment.yaml") + t)


if __name__ == "__main__":
    build_layers()
    build_prompt()
    build_configmap()
    build_deployment()
    print("wrote layers-input.private.json, system-prompt.private.md, k8s/private-{configmap,deployment}.yaml")
