#!/usr/bin/env bash
# Generate k8s/content-configmap.yaml from source files.
# Run from the repo root: bash scripts/generate-configmap.sh
set -euo pipefail

cd "$(dirname "$0")/.."

cat > k8s/content-configmap.yaml <<'HEADER'
# DO NOT EDIT THIS FILE DIRECTLY.
# It is generated from source files by: bash scripts/generate-configmap.sh
# Edit layers-input.json, index.html, or system-prompt.md instead.
HEADER

kubectl create configmap bosl-high-seas-content \
  --from-file=index.html=index.html \
  --from-file=layers-input.json=layers-input.json \
  --from-file=system-prompt.md=system-prompt.md \
  --dry-run=client -o yaml >> k8s/content-configmap.yaml

echo "Generated k8s/content-configmap.yaml"
